
-- SCRIPT DE CRIACAO E POPULACAO BD --

DROP TABLE AJUDA;
DROP TABLE LOG_ACESSO_USUARIO;
DROP TABLE TAREFA;
DROP TABLE STATUS_TAREFA;
DROP TABLE PROJETO_USUARIO;
DROP TABLE PROJETO;
DROP TABLE USUARIO;
DROP TABLE NIVEL_ACESSO;

CREATE TABLE AJUDA
(
CD_AJUDA           INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
CD_TAREFA          INTEGER NOT NULL ,
CD_PROJETO_USUARIO INTEGER NOT NULL
) ;

CREATE TABLE LOG_ACESSO_USUARIO
  (
    CD_LOG_ACESSO_USUARIO INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    DT_ACESSO             DATE NOT NULL ,
    CD_USUARIO            INTEGER NOT NULL
  ) ;

CREATE TABLE NIVEL_ACESSO
(
CD_NIVEL_ACESSO INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
NM_NIVEL_ACESSO VARCHAR (100) NOT NULL
) ;

CREATE TABLE PROJETO
(
CD_PROJETO              INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
NM_PROJETO              VARCHAR (100) NOT NULL ,
DC_PROJETO              VARCHAR (255) ,
CD_COORDENADOR          INTEGER NOT NULL ,
DT_INICIO               DATE NOT NULL ,
DT_PREVISAO_FINALIZACAO DATE NOT NULL
) ;


CREATE TABLE PROJETO_USUARIO
(
CD_PROJETO_USUARIO INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
CD_USUARIO         INTEGER NOT NULL ,
CD_PROJETO         INTEGER NOT NULL
) ;

CREATE TABLE STATUS_TAREFA
(
CD_STATUS INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
NM_STATUS VARCHAR (100) NOT NULL
) ;

CREATE TABLE TAREFA
(
CD_TAREFA          INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
NM_TAREFA          VARCHAR (100) NOT NULL ,
DC_TAREFA          VARCHAR (255) ,
DC_FERRAMENTA       VARCHAR (255) ,
CD_PROJETO_USUARIO INTEGER NOT NULL ,
DT_FINALIZACAO     DATE NOT NULL ,
CD_STATUS          INTEGER NOT NULL
) ;

CREATE TABLE USUARIO
(
CD_USUARIO      INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
NM_LOGIN        VARCHAR (100) NOT NULL ,
NM_SENHA        VARCHAR (100) NOT NULL ,
NM_USUARIO      VARCHAR (100) NOT NULL ,
NM_EMAIL        VARCHAR (255) NOT NULL ,
NR_TELEFONE     VARCHAR (20) ,
CD_NIVEL_ACESSO INTEGER NOT NULL
) ;

ALTER TABLE LOG_ACESSO_USUARIO ADD FOREIGN KEY ( CD_USUARIO ) REFERENCES USUARIO ( CD_USUARIO ) ;

ALTER TABLE PROJETO ADD FOREIGN KEY ( CD_COORDENADOR ) REFERENCES USUARIO ( CD_USUARIO ) ;

ALTER TABLE PROJETO_USUARIO ADD FOREIGN KEY ( CD_PROJETO ) REFERENCES PROJETO ( CD_PROJETO ) ;

ALTER TABLE PROJETO_USUARIO ADD FOREIGN KEY ( CD_USUARIO ) REFERENCES USUARIO ( CD_USUARIO ) ;

ALTER TABLE AJUDA ADD FOREIGN KEY ( CD_PROJETO_USUARIO ) REFERENCES PROJETO_USUARIO ( CD_PROJETO_USUARIO ) ;

ALTER TABLE AJUDA ADD FOREIGN KEY ( CD_TAREFA ) REFERENCES TAREFA ( CD_TAREFA ) ;

ALTER TABLE TAREFA ADD FOREIGN KEY ( CD_PROJETO_USUARIO ) REFERENCES PROJETO_USUARIO ( CD_PROJETO_USUARIO ) ;

ALTER TABLE TAREFA ADD FOREIGN KEY ( CD_STATUS ) REFERENCES STATUS_TAREFA ( CD_STATUS ) ;

ALTER TABLE USUARIO ADD FOREIGN KEY ( CD_NIVEL_ACESSO ) REFERENCES NIVEL_ACESSO ( CD_NIVEL_ACESSO ) ;

---------------------

INSERT INTO NIVEL_ACESSO(NM_NIVEL_ACESSO) VALUES('ADMINISTRADOR');
INSERT INTO NIVEL_ACESSO(NM_NIVEL_ACESSO) VALUES('GERENTE');
INSERT INTO NIVEL_ACESSO(NM_NIVEL_ACESSO) VALUES('DESENVOLVEDOR');

INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('JOSEVICTOR', 'JOSE@12', 'JOSE VICTOR', 'JOSEVICTOR@GMAIL.COM', '56564854', 1);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('THOMAZ', 'THOMAZ@12', 'THOMAZ', 'THOMAZ@GMAIL.COM', '84629422', 1);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('ADMIN', 'ADMIN', 'ADMIN', 'ADMIN@ADMIN.COM', '84538622', 1);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('JOAO', 'JOAO@12', 'JOAO', 'JOAO@GMAIL.COM', '84645393', 2);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('MARIA', 'MARIA@12', 'MARIA', 'MARIA@GMAIL.COM', '864349384', 2);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('BRUNO', 'BRUNO@12', 'BRUNO', 'BRUNO@GMAIL.COM', '54972872', 3);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('LARISSA', 'LARISSA@12', 'LARISSA', 'LARISSA@GMAIL.COM', '864364389', 3);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('LUCAS', 'LUCAS@12', 'LUCAS', 'LUCAS@GMAIL.COM', '94378383', 3);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('GABRIEL', 'GABRIEL@12', 'GABRIEL', 'GABRIEL@GMAIL.COM', '94378383', 3);
INSERT INTO USUARIO(NM_LOGIN, NM_SENHA, NM_USUARIO, NM_EMAIL, NR_TELEFONE, CD_NIVEL_ACESSO) VALUES('MARCO', 'MARCO@12', 'MARCO', 'MARCO@GMAIL.COM', '94378383', 3);

INSERT INTO PROJETO(NM_PROJETO, DC_PROJETO, CD_COORDENADOR, DT_INICIO, DT_PREVISAO_FINALIZACAO) VALUES('SISTEMA BANCARIO', 'PROJETO DE DESENVOLVIMENTO DE UM SISTEMA BANCARIO', 4, '2016-01-01', '2016-06-30');
INSERT INTO PROJETO(NM_PROJETO, DC_PROJETO, CD_COORDENADOR, DT_INICIO, DT_PREVISAO_FINALIZACAO) VALUES('SISTEMA UNIVERSITARIO', 'PROJETO DE DESENVOLVIMENTO DE UM SISTEMA UNIVERSITARIO', 4, '2016-03-15', '2016-10-01');
INSERT INTO PROJETO(NM_PROJETO, DC_PROJETO, CD_COORDENADOR, DT_INICIO, DT_PREVISAO_FINALIZACAO) VALUES('SISTEMA INVENTARIO', 'PROJETO DE DESENVOLVIMENTO DE UM SISTEMA DE INVENTARIO', 4, '2016-01-15', '2016-08-30');
INSERT INTO PROJETO(NM_PROJETO, DC_PROJETO, CD_COORDENADOR, DT_INICIO, DT_PREVISAO_FINALIZACAO) VALUES('APLICATIVO MAPAS', 'PROJETO DE DESENVOLVIMENTO DE UM APLICATIVO DE MAPAS', 5, '2016-06-01', '2017-01-31');
INSERT INTO PROJETO(NM_PROJETO, DC_PROJETO, CD_COORDENADOR, DT_INICIO, DT_PREVISAO_FINALIZACAO) VALUES('APLICATIVO PAQUERA', 'PROJETO DE DESENVOLVIMENTO DE UM APLICATIVO DE PAQUERA', 5, '2016-01-01', '2016-06-30');

INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(6,1); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(7,1); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(8,1); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(9,1); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(10,1); 

INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(6,2); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(7,2); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(8,2); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(9,2);
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(10,2); 

INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(6,3); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(7,3); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(8,3); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(9,3);
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(10,3); 

INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(8,4); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(9,4);
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(10,4);

INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(8,5); 
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(9,5);
INSERT INTO PROJETO_USUARIO(CD_USUARIO,CD_PROJETO) VALUES(10,5);

INSERT INTO STATUS_TAREFA(NM_STATUS) VALUES('Nao iniciada');
INSERT INTO STATUS_TAREFA(NM_STATUS) VALUES('Iniciada');
INSERT INTO STATUS_TAREFA(NM_STATUS) VALUES('Incompleta');
INSERT INTO STATUS_TAREFA(NM_STATUS) VALUES('Finalizando');
INSERT INTO STATUS_TAREFA(NM_STATUS) VALUES('Teste');
INSERT INTO STATUS_TAREFA(NM_STATUS) VALUES('Concluida');
INSERT INTO STATUS_TAREFA(NM_STATUS) VALUES('Cancelada');


INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Login', 'Implementar login de usuário', 1, '2016-03-15', 'Netbeans', 1);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('BD', 'Criação do Banco de Dados', 2, '2016-03-10', 'Oracle', 5);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('População inicial do BD', 'População inicial do ', 2, '2016-03-15', 'Oracle', 2);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Documentação BD', 'Documentação BD', 2, '2016-03-30', 'Documentação', 1);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('JSTL', 'Implementaçãodo JSTL', 3, '2016-04-19', 'Netbeans', 3);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Web', 'Implementação da parte Web', 4, '2016-04-20', 'Netbeans', 4);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Casos de Uso', 'Modelagem dos Casos de Uso', 5, '2016-02-18', 'Star UML', 6);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Casos de Uso', 'Modelagem dos Casos de Uso', 6, '2016-04-16', 'Star UML', 1);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Diagrama de Classes', 'Criação do modelo do diagrama de classes', 7, '2016-04-20', 'Star UML', 2);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('BPMN', 'Modelagem do BPMN', 8, '2016-04-25', 'Star UML', 3);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Documento de Visão', 'Finalização do Documento de Visão', 9, '2016-04-15', 'Word', 4);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Diagrama de Atividades', 'Modelagem do Diagrama de Atividades', 10, '2016-04-20', 'Star UML', 6);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Documento de Visão', 'Criação do Documento de Visão', 11, '2016-05-20', 'Word', 2);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Implementação', 'Implementação das classes base', 12, '2016-05-30', 'Netbeans', 1);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Entrevista', '3ª entrevista com clientes', 13, '2016-05-15', 'Word', 7);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Brainstorm', 'Levantamento de requisitos', 14, '2016-05-10', 'One Note', 6);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Diagrama de Classes', 'Modelagem do Diagrama de Classes', 15, '2016-05-23', 'Star UML', 3);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Brainstorm', 'Levantamento de requisitos', 16, '2016-05-18', 'One Note', 6);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('TDD Login', 'Realizar TDD da validação do Login', 17, '2016-05-10', 'Netbeans', 5);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('CSS', 'Implementação do design da parte Web', 18, '2016-05-12', 'Netbeans', 1);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('TDD Usuário', 'Realizar o TDD com o CRUD do usuário', 19, '2016-03-19', 'Netbeans', 5);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Diagrama de Sequência', 'Finalização do Diagrama de Sequência', 20, '2016-03-14', 'Star UML', 4);
INSERT INTO TAREFA(NM_TAREFA, DC_TAREFA, CD_PROJETO_USUARIO, DT_FINALIZACAO, DC_FERRAMENTA, CD_STATUS) VALUES('Brainstorm', 'Levantamento de requisitos', 21, '2016-03-02', 'One Note', 7);

--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(1,4);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(3,1);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(4,2);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(5,3);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(6,4);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(7,5);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(8,6);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(9,7);
--INSERT INTO AJUDA(CD_TAREFA, CD_PROJETO_USUARIO) VALUES(10,8);